# Generated by Django 4.2.5 on 2023-09-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0002_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Profile'),
        ),
    ]
