# Generated by Django 4.2.5 on 2023-09-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0003_alter_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
