# Generated by Django 4.2.5 on 2023-09-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logapp", "0004_remove_user_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, default="default-logo.jpg", upload_to="users-images"
            ),
        ),
    ]
