# Generated by Django 4.2.5 on 2023-09-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logapp", "0005_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(upload_to="images/users-images"),
        ),
    ]
