# Generated by Django 4.2.5 on 2023-09-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logapp", "0006_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
