# Generated by Django 5.0.6 on 2024-07-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0012_alter_user_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
