# Generated by Django 4.2.5 on 2023-09-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainAdvertisement',
            new_name='SlideImages',
        ),
        migrations.AlterModelOptions(
            name='slideimages',
            options={'ordering': ['-time_create', 'title']},
        ),
    ]
