# Generated by Django 4.2.5 on 2023-12-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slideimages_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlideImages',
        ),
    ]
