# Generated by Django 4.2.5 on 2023-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shippingadress_payee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsgallery',
            options={'ordering': ['created'], 'verbose_name': 'Product', 'verbose_name_plural': 'ProductsGallery'},
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=100),
        ),
    ]
