# Generated by Django 4.2.5 on 2023-12-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_productcategory_products_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
