# Generated by Django 4.2.5 on 2023-12-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_rename_ownergroupmanager_ownergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="ontest",
            field=models.BooleanField(default=True),
        ),
    ]
