# Generated by Django 4.2.5 on 2024-04-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_rename_date_odered_favourite_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favouriteitem",
            name="offer",
        ),
        migrations.AddField(
            model_name="favouriteitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.products",
            ),
        ),
    ]
