# Generated by Django 4.2.5 on 2024-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_orderinfo_product_orderinfo_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffers',
            name='availability',
            field=models.IntegerField(default=0),
        ),
    ]
