# Generated by Django 4.2.5 on 2024-04-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_productoffers_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productoffers',
            name='price',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
