# Generated by Django 4.2.5 on 2024-04-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_productoffers_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsgallery',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
        ),
    ]
