# Generated by Django 4.2.5 on 2024-04-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_remove_products_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favouriteitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.products",
            ),
        ),
    ]
