# Generated by Django 4.2.5 on 2024-04-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_favouriteitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
