# Generated by Django 4.2.5 on 2024-05-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0026_orderrequests"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrequests",
            name="shipping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.shippingadress",
            ),
        ),
    ]
