# Generated by Django 5.0.6 on 2024-06-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0027_orderrequests_shipping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
