# Generated by Django 5.0.6 on 2024-06-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0028_alter_products_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="online_status",
            field=models.BooleanField(default=False),
        ),
    ]
