# Generated by Django 5.0.6 on 2024-07-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_favourite_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteitem',
            name='favourite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.favourite'),
        ),
    ]
