# Generated by Django 4.2.5 on 2024-01-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rooms', '0002_chats_alter_messages_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='participants',
        ),
    ]
