# Generated by Django 5.0.6 on 2024-07-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_rooms", "0004_messages_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chats",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
