name: Aerapolisi CI
on: 
  push:
    paths-ignore:
      - '**/README.md'
jobs:
  test-app:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11.5"]
    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_NAME:   ${{ vars.DATABASE_NAME }}
      DATABASE_USER: ${{ vars.DATABASE_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 5432
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: | 
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
          pip install black
      - name: run Django tests
        run: |
          cd aerapolisi
          python manage.py test
      - name: run linter tests
        run: black --check
        
        
      


